// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Plainion.WhiteBoard")]
[assembly: AssemblyProductAttribute("Plainion.WhiteBoard")]
[assembly: AssemblyDescriptionAttribute("Plainion.WhiteBoard")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2018")]
[assembly: AssemblyVersionAttribute("1.2.0")]
[assembly: AssemblyFileVersionAttribute("1.2.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.WhiteBoard";
        internal const System.String AssemblyProduct = "Plainion.WhiteBoard";
        internal const System.String AssemblyDescription = "Plainion.WhiteBoard";
        internal const System.String AssemblyCopyright = "Copyright @ 2018";
        internal const System.String AssemblyVersion = "1.2.0";
        internal const System.String AssemblyFileVersion = "1.2.0";
    }
}
